# Generated by Django 3.2.3 on 2022-03-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0008_auto_20220323_0008'),
        ('login_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognizer.lectruemodel'),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognizer.teacherprofilemodel'),
        ),
    ]
