# Generated by Django 3.2.3 on 2022-03-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0010_auto_20220324_0350'),
        ('login_details', '0002_auto_20220323_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_details_with_teacher', to='recognizer.teacherprofilemodel'),
        ),
    ]
