# Generated by Django 2.2.19 on 2021-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=2),
        ),
    ]
