# Generated by Django 2.2.19 on 2021-05-03 20:16

from django.db import migrations, models
import recognizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0002_auto_20210504_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recognizer.models.user_image_path),
        ),
    ]
