# Generated by Django 2.2.19 on 2021-05-05 06:17

from django.db import migrations, models
import recognizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0003_auto_20210504_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=recognizer.models.user_image_path),
        ),
    ]
