# Generated by Django 3.2.3 on 2022-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0005_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, choices=[('LDCE', 'LALBHAI DALPATBHAI COLLEGE OF ENGINEERING'), ('NIR', 'NIRMA INSTITUTE'), ('VGCE', 'VISHVAKARMA COLLEGE OF ENGINEERING')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enrollment_number',
            field=models.IntegerField(default='190280111140'),
        ),
    ]
