# Generated by Django 2.2.19 on 2021-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0005_auto_20210505_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='User_images/'),
        ),
    ]
