# Generated by Django 3.2.3 on 2022-03-22 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_details', '0001_initial'),
        ('recognizer', '0007_teacherprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='TeacherProfileModel',
        ),
        migrations.CreateModel(
            name='LectrueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(default='', max_length=100)),
                ('associeted_teacher', models.ManyToManyField(blank=True, to='recognizer.TeacherProfileModel')),
            ],
        ),
    ]
