# Generated by Django 2.2.19 on 2021-05-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0007_auto_20210506_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_proceed',
            field=models.BooleanField(default=False),
        ),
    ]
