# Generated by Django 3.2.3 on 2022-03-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0008_auto_20220323_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectruemodel',
            name='branch',
            field=models.CharField(blank=True, choices=[('EC', 'ELECTRONICS AND COMMUNICATION'), ('CE', 'COMPUTER ENGINEERING'), ('IT', 'INFORMATION AND TECHNOLOGY')], max_length=5, null=True),
        ),
    ]
