# Generated by Django 2.2.19 on 2021-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0008_userprofile_login_proceed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(default='1234567890'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
