# Generated by Django 2.2.19 on 2021-05-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognizer', '0010_auto_20210511_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
